spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jackson:
      time-zone: GMT+8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hospitalsystem?serverTimezone=Asia/Shanghai
    username: root
    password: wyh12345


mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
#  configuration:
#          log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  config: classpath:logback-spring.xml

